# Generated by Django 4.2.2 on 2023-11-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(default=None, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='links',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='practical',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price_details',
            field=models.CharField(default=None, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_of_post',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default=None, max_length=264, null=True),
        ),
    ]
