# Generated by Django 4.2.2 on 2023-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0004_alter_module_description_alter_module_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subject',
            field=models.CharField(default=None, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
