# Generated by Django 4.2.2 on 2023-12-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0005_alter_workshop_subject_alter_workshop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default='False'),
        ),
    ]
