# Generated by Django 4.2.2 on 2023-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0006_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(default='https://live.staticflickr.com/5520/11007151534_ade9088019_k.jpg', max_length=264, null=True),
        ),
    ]
