# Generated by Django 4.2.2 on 2023-12-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0007_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
