# Generated by Django 4.2.2 on 2023-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0008_module_end_date_module_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
