# Generated by Django 4.2.2 on 2023-12-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0009_rename_time_workshop_end_time_workshop_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
