# Generated by Django 4.2.2 on 2023-12-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0012_comment_by_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio_image',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='setcourse.course'),
        ),
    ]
