# Generated by Django 4.2.2 on 2023-12-14 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0013_alter_student_bio_image_alter_student_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
