# Generated by Django 4.2.2 on 2023-12-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setcourse', '0015_rename_student_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrolled',
            new_name='course',
        ),
    ]
